NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [12]:
import numpy as np

np.zeros((4,3))
np.ones((3,3))
np.linspace(0,20,5);np.arange(0, 21, 5)
np.linspace(0,1,4)
np.random.randn(2, 2)  # 2x3 배열


array([[-0.51826975, -0.1404379 ],
       [ 0.66556174, -0.88575469]])

1. 배열 `arr`에서 1번째 열만 추출
2. 배열 `arr`에서 2번째 행, 3번째 열의 값을 출력
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [19]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[:,0:1])
print(arr[1:2,2:3])
print(arr[1:3,0:2])


[[10]
 [40]
 [70]]
[[60]]
[[40 50]
 [70 80]]


아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출

arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [24]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[[0,2,4]])
print(arr[arr>50])


[10 30 50]
[60 70]


어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

In [43]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

print(sales[sales>=200])
print(sales[sales[:,2] <= 100, :2])
print(sales[sales[:,1] <= 150, :])



[200 220 300 320 310]
[[120 150]
 [ 50  45]]
[[120 150 100]
 [ 80  90 110]
 [ 50  45  70]]


다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [54]:
first = np.array([200, 340, 150, 400])
second = np.array([220, 300, 180, 420])
third = np.vstack((first,second))
print(third)
third.mean(axis=0)

[[200 340 150 400]
 [220 300 180 420]]


array([210., 320., 165., 410.])

다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [62]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)



[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


다음 두 배열 간의 내적 연산을 수행하세요.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [65]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.dot(arr1,arr2))


32


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

In [66]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(arr2d+arr1d)

[[11 22 33]
 [14 25 36]]


1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.
arr = np.array([10, 20, 30, 40, 50])

In [70]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr>20])
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())

[30 40 50]
150
50
10
30.0


아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.
arr = np.array([10, 20, 30, 30, 40, 50, 60])

In [74]:
from scipy import stats
arr = np.array([10, 20, 30, 30, 40, 50, 60])
print(arr.mean())
print(stats.mode(arr))
print(np.var(arr))
print(np.std(arr))
print(arr.max()-arr.min())

34.285714285714285
ModeResult(mode=np.int64(30), count=np.int64(2))
253.06122448979593
15.90789817951435
50


정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성

In [77]:
print(np.random.randn(1000))
print(np.linspace(0,1,1000))

[ 1.95869652e-01  1.11852573e+00 -7.53635172e-01  6.08201726e-01
  1.54681248e+00 -2.04257567e-01  1.39020393e-01 -6.07871347e-01
 -1.04868304e-01 -1.19068007e-01  4.11243930e-01 -9.51052862e-01
  7.68979638e-01 -8.64865628e-01  6.64228379e-01 -1.82794349e+00
  6.06202972e-02  1.48943086e-01 -9.94875147e-01 -1.32388806e+00
  1.15048241e+00  1.16863423e+00 -1.40124087e+00 -1.01268857e+00
  1.21387083e+00 -3.40880516e-01  1.12127144e-01 -4.33726858e-01
  3.67931602e-02 -7.25517651e-01  2.95009594e-01  1.48628224e+00
 -9.14662523e-01 -3.68096717e-01 -3.07695812e-01  1.00381915e+00
 -4.42696938e-01  7.44493723e-01  1.20272480e+00  5.48749308e-01
 -1.47587041e-01 -5.71323915e-01 -1.81013143e-01 -9.30690580e-01
 -3.69659002e-01  9.01638333e-01  9.53373856e-01  8.81116460e-01
 -7.40226510e-01 -7.04574209e-01 -1.53759372e+00 -1.53625159e+00
 -2.41274326e+00  1.15375774e+00  3.19358484e-01  5.21311611e-01
 -1.07875196e+00  1.64086185e+00  5.92618980e-01  9.66357786e-03
  4.10279577e-01  3.72047

아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.
# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

In [80]:
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

scores = np.array((scores_math,scores_english,scores_science))
mean_scores = scores.mean(axis=0)
print(mean_scores)
print(np.var(mean_scores))
print(np.std(mean_scores))

[87.66666667 88.33333333 79.33333333 87.         93.66666667 89.
 87.33333333 89.66666667 85.         87.66666667]
11.89333333333335
3.4486712417006857


다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.
arr = np.array([50, 10, 30, 40, 20])

In [86]:
arr = np.array([50, 10, 30, 40, 20])

print(np.sort(arr))
print(np.sort(arr)[::-1])

[10 20 30 40 50]
[50 40 30 20 10]


다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.
arr2d = np.array([[8, 3, 5], [2, 9, 1]])

In [93]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
print(np.sort(arr2d))
print(np.sort(arr2d, axis=0))


[[3 5 8]
 [1 2 9]]
[[2 3 1]
 [8 9 5]]


다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.
arr = np.array([15, 10, 20])

In [97]:
arr = np.array([15, 10, 20])

print(arr[arr.argsort()])

[10 15 20]


다음 두 개의 1차원 배열을 np.concatenate()와 np.hstack()을 사용하여 병합하세요.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [102]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.concatenate((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


다음 2개의 1차원 배열을 np.stack()을 사용하여 새로운 축을 따라 병합하세요.

In [106]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.stack((arr1,arr2)))


[[1 2 3]
 [4 5 6]]


TypeError: stack() got an unexpected keyword argument 'asix'

다음 두 개의 2차원 배열을 np.concatenate()와 np.vstack()을 사용하여 각각 병합하세요.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [107]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.concatenate((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

데이터 (각 지점의 월별 과일 판매량(단위: 개))


In [112]:

import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

# 1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
print(sales_data.mean(axis=2))


[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]


In [161]:
# 2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
fruits = np.array(["apples","banana","orange"])
sum_num = sales_data.sum(axis=0)
print(sum_num)
arg_max = np.argmax(sum_num,axis=0)
print(sum_num.max(axis=0))
print(fruits[arg_max])


[[520 620 750 860 760 830]
 [430 515 600 670 645 655]
 [380 510 630 610 550 580]]
[520 620 750 860 760 830]
['apples' 'apples' 'apples' 'apples' 'apples' 'apples']


In [ ]:
# 3. 6개월 동안 전체 지점에서 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
fruits = np.array(["apples","banana","orange"])
sum_num = sales_data.sum(axis=(0,2))
print(sum_num)
arg_max = np.argmax(sum_num)
print(fruits[arg_max])

[4340 3515 3260]
apples


In [196]:
# 4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
#print(sales[sales[:,1]>=150,:])
a = sales_data[:,:]>=150
#print(a)
b = np.argwhere(a)
for i in b:
    print(str(i[0]+1)+"지점 "+str(i[2]+1)+"월 "+fruits[i[1]])

1지점 2월 apples
1지점 3월 apples
1지점 4월 apples
1지점 5월 apples
1지점 6월 apples
1지점 3월 banana
1지점 4월 banana
1지점 5월 banana
1지점 6월 banana
1지점 3월 orange
1지점 6월 orange
3지점 3월 apples
3지점 4월 apples
3지점 5월 apples
3지점 6월 apples
3지점 4월 banana
3지점 6월 banana
4지점 3월 apples
4지점 4월 apples
4지점 5월 apples
4지점 6월 apples
