NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [9]:
import numpy as np
print(np.zeros((4,3)))
print(np.ones((3,3)))
print(np.arange(0,21,5))
print(np.linspace(0,1,4))
print(np.random.randn(2,2))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0  5 10 15 20]
[0.         0.33333333 0.66666667 1.        ]
[[ 0.47742836 -0.31710325]
 [-0.44521243 -0.37411203]]


1. 배열 `arr`에서 1번째 열만 추출
2. 배열 `arr`에서 2번째 행, 3번째 열의 값을 출력
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [61]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[:,0])
print(arr[1,2])
print(arr[0:2,0:2])


[10 40 70]
60
[[10 20]
 [40 50]]


아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출

arr = np.array([10, 20, 30, 40, 50, 60, 70])

In [62]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[[0,2,4]])
print(arr[arr>50])


[10 30 50]
[60 70]


어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

In [64]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])
print(sales[sales >= 200])
print(sales[sales[:,2]<=100,:2])
print(sales[sales[:,1]>=150,:])


[200 220 300 320 310]
[[120 150]
 [ 50  45]]
[[120 150 100]
 [200 180 220]
 [300 320 310]]


다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [49]:
first = np.array([200, 340, 150, 400])
second = np.array([220, 300, 180, 420])
print(first + second)
print((first+second)/2 )

[420 640 330 820]
[210. 320. 165. 410.]


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [50]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


다음 두 배열 간의 내적 연산을 수행하세요.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [51]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1, arr2))

32


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

In [65]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
print(arr2d+arr1d)


[[11 22 33]
 [14 25 36]]


1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.
arr = np.array([10, 20, 30, 40, 50])

In [72]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr>20])

print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.std())
print(arr.var())
print(arr.cumsum())


[30 40 50]
150
50
10
30.0
14.142135623730951
200.0
[ 10  30  60 100 150]


아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.
arr = np.array([10, 20, 30, 30, 40, 50, 60])

In [83]:
from scipy import stats

arr = np.array([10, 20, 30, 30, 40, 50, 60])
print(np.mean(arr))
print(np.median(arr))
print(stats.mode(arr))
print(np.std(arr))
print(np.var(arr))
print(np.max(arr)-np.min(arr))

34.285714285714285
30.0
ModeResult(mode=np.int64(30), count=np.int64(2))
15.90789817951435
253.06122448979593
50


정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성

In [111]:
arr1 = np.random.randn(1000)  # 평균 0, 표준편차 1인 정규분포 난수 1000개
arr2 = np.random.uniform(0, 1, 1000)  # 0과 1 사이의 균등분포 난수 1000개
print(np.mean(arr1), np.std(arr1))
print(np.mean(arr2), np.std(arr2))
print(arr2)


-0.012268065182706175 0.9682957496229677
0.5034754569286708 0.2847293111926032
[0.46563067 0.1323508  0.05424135 0.83508547 0.89976412 0.26291932
 0.95670358 0.29579805 0.39973224 0.16160807 0.7906184  0.91419387
 0.27332965 0.14226468 0.61555707 0.2209723  0.31812337 0.16982209
 0.80102134 0.10394847 0.9795028  0.17129697 0.62845822 0.25925995
 0.97606445 0.76212823 0.09113953 0.83247598 0.59209708 0.01323566
 0.21122885 0.42012715 0.74073509 0.10845012 0.8539825  0.22335023
 0.33468882 0.1815406  0.47418114 0.89693066 0.0556582  0.05454929
 0.61571894 0.31092149 0.57781411 0.12083677 0.51825256 0.66677971
 0.48040367 0.99591531 0.70683    0.55071543 0.52612106 0.17412875
 0.32838524 0.5950546  0.2529411  0.73731083 0.0216522  0.45632225
 0.18539199 0.53643586 0.85985422 0.50097899 0.11742    0.46865422
 0.23485571 0.9928807  0.65431467 0.75692848 0.0035442  0.91746872
 0.46536007 0.03947838 0.33962164 0.25744003 0.79094987 0.91578554
 0.39120215 0.21619507 0.03589666 0.30335558 0.353

아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.
# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

In [120]:
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

score = np.array([scores_math,scores_english,scores_science])
mean_score = score.mean(axis=0)
print(np.var(mean_score))
print(np.std(mean_score))



11.89333333333335
3.4486712417006857


다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.
arr = np.array([50, 10, 30, 40, 20])

In [122]:
arr = np.array([50, 10, 30, 40, 20])
print(np.sort(arr))
print(np.sort(arr)[::-1])

[10 20 30 40 50]
[50 40 30 20 10]


다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.
arr2d = np.array([[8, 3, 5], [2, 9, 1]])

In [129]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])

print(np.sort(arr2d, axis = 0))
print("##############################")
print(np.sort(arr2d, axis = 1))


[[2 3 1]
 [8 9 5]]
##############################
[[3 5 8]
 [1 2 9]]


다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.
arr = np.array([15, 10, 20])

In [131]:
arr = np.array([15, 10, 20])
print(np.argsort(arr))
print(arr[np.argsort(arr)])

[1 0 2]
[10 15 20]


다음 두 개의 1차원 배열을 np.concatenate()와 np.hstack()을 사용하여 병합하세요.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [164]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.hstack((arr1,arr2)))
print(np.concatenate((arr1,arr2),axis=1))


[[1 2 3 4 5 6]]
[[1 2 3 4 5 6]]


다음 2개의 1차원 배열을 np.stack()을 사용하여 새로운 축을 따라 병합하세요.

In [162]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.stack((arr1,arr2),axis=0))
print(np.stack((arr1,arr2),axis=1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


다음 두 개의 2차원 배열을 np.concatenate()와 np.vstack()을 사용하여 각각 병합하세요.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

데이터 (각 지점의 월별 과일 판매량(단위: 개))


In [242]:

import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

print(1)
print(sales_data.mean(axis=2))

print(2)
# 2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
a = sales_data.max(axis=0)
b = a.max(axis=0)
c,d = np.where(a==b)
print(b)
e = np.array(c)
fruit = np.array(["사과", "바나나", "오렌지"])[c]
print(fruit)

print(3)
# 3 전체 지점에서 과일별 총 판매량을 구하고, 가장 많이 판매된 과일을 찾는다.
fruit = np.array(["사과", "바나나", "오렌지"])
a = sales_data.sum(axis=0)
b = a.sum(axis=1)
c = b.argsort()
print(b)
print(fruit[c][0])



1
[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]
2
[130 150 200 230 180 210]
['사과' '사과' '사과' '사과' '사과' '사과']
3
[4340 3515 3260]
오렌지


In [250]:
# 4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
#print(sales[sales[:,1]>=150,:])
fruits = np.array(["사과", "바나나", "오렌지"])

mask = sales_data >= 150
locations = np.argwhere(mask)
#print(locations)

for loc in locations:
    site, fruit, month = loc
    print(f"지점 : {site+1}, 과일명 : {fruits[fruit]}, {month+1}월 : {sales_data[site, fruit, month]}")

지점 : 1, 과일명 : 사과, 2월 : 150
지점 : 1, 과일명 : 사과, 3월 : 200
지점 : 1, 과일명 : 사과, 4월 : 230
지점 : 1, 과일명 : 사과, 5월 : 180
지점 : 1, 과일명 : 사과, 6월 : 210
지점 : 1, 과일명 : 바나나, 3월 : 170
지점 : 1, 과일명 : 바나나, 4월 : 190
지점 : 1, 과일명 : 바나나, 5월 : 160
지점 : 1, 과일명 : 바나나, 6월 : 180
지점 : 1, 과일명 : 오렌지, 3월 : 160
지점 : 1, 과일명 : 오렌지, 6월 : 150
지점 : 3, 과일명 : 사과, 3월 : 160
지점 : 3, 과일명 : 사과, 4월 : 180
지점 : 3, 과일명 : 사과, 5월 : 170
지점 : 3, 과일명 : 사과, 6월 : 190
지점 : 3, 과일명 : 바나나, 4월 : 150
지점 : 3, 과일명 : 바나나, 6월 : 160
지점 : 4, 과일명 : 사과, 3월 : 150
지점 : 4, 과일명 : 사과, 4월 : 170
지점 : 4, 과일명 : 사과, 5월 : 160
지점 : 4, 과일명 : 사과, 6월 : 180


In [243]:
# 2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
a = sales_data.max(axis=0)
b = a.max(axis=0)
print(np.argmax(b))
c,d = np.where(a==b)
print(b)
e = np.array(c)
fruit = np.array(["사과", "바나나", "오렌지"])[c]
print(fruit)

3
[130 150 200 230 180 210]
['사과' '사과' '사과' '사과' '사과' '사과']
