In [4]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
b = np.array([4, 5, 6,6])
c = a + b
print(c)

[1 2 3 4]
[ 5  7  9 10]


In [5]:
print(a.shape)  # 배열의 차원
print(a.size)   # 배열의 총 원소 개수

(4,)
4


In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [ ]:
arr = np.zeros((2, 3))  # 2x3 배열
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
print(np.ones((3,4))) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
print(np.arange(0, 10, 2) )

[0 2 4 6 8]


In [16]:
print(np.linspace(0,1))

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [17]:
print(np.random.randn(2, 3))

[[-0.4761805  -0.80219895  0.51513473]
 [ 1.31584235 -0.74123732 -0.61864637]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

(1, 3)


In [21]:
print(arr.ndim)
print(arr.size)  # 총 6개의 원소
print(arr.dtype)  # int64

2
3
int64


In [27]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[2])
print(arr[4])


10
30
50


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 1])
print(arr[2, 2])

2
9


In [35]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 0, 2]) 
print(arr[0,1,1])
print(arr[1,1,2])

9
5
12


In [39]:
arr = np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[:3])

[20 30 40]
[10 20 30]


In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1:,:2])

[[4 5]
 [7 8]]


In [60]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[:, 1, :2])  # 각 차원에서 1번째 행의 처음 두 열 출력 ([[4, 5], [10, 11]])

[[ 4  5]
 [10 11]]


In [57]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # 0번째, 2번째, 4번째 인덱스를 선택
print(arr[idx])   # [10, 30, 50]

[10 30 50]


In [65]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 1, 2]
cols = [2, 1, 0]
print(arr[rows, cols])

[3 5 7]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 30])


[40 50]


In [67]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[arr > 4])

[5 6 7 8 9]


In [70]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [71]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dot(arr1, arr2)) 

32


In [73]:
arr2d = np.array([[1, 2], [3, 4]])
arr1d = np.array([5, 6])
print(np.dot(arr2d, arr1d))

[17 39]


In [77]:
arr2d_1 = np.array([[1, 2], [3, 4]])
arr2d_2 = np.array([[5, 6], [7, 8]])

print(arr2d_1)
print(arr2d_2)
print("")
print(np.dot(arr2d_1, arr2d_2))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[19 22]
 [43 50]]


In [74]:
arr = np.array([1, 2, 3])
print(arr + 10) 

[11 12 13]


In [78]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([1, 2, 3])
print(arr2d + arr1d)
# [[2, 4, 6],
#  [5, 7, 9]]

[[2 4 6]
 [5 7 9]]


In [94]:
arr3d = np.random.randn(2,1,2)
arr2d = np.random.randn(2,2)
print(arr3d)
print("########################################################################")
print(arr2d)
print("########################################################################")

print(arr3d + arr2d)

[[[ 0.10612577  2.97140618]]

 [[-0.77222299  1.13259124]]]
########################################################################
[[ 0.46909117 -1.24491092]
 [-0.33532562  0.58807377]]
########################################################################
[[[ 0.57521694  1.72649526]
  [-0.22919985  3.55947995]]

 [[-0.30313182 -0.11231968]
  [-1.10754861  1.720665  ]]]


In [97]:
arr2d = np.array(
    [[1,2,3],
     [4,5,6]]
)
row = np.array([10,20,30])
col = np.array([
        [10],
        [20]
    ])
print(arr2d.shape)
print(row.shape)
print(col.shape)

print(arr2d + row)
print(arr2d + col)

(2, 3)
(3,)
(2, 1)
[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [24 25 26]]


In [98]:
arr = np.array([10, 20, 30])
print(arr > 15)  # [False, True, True]
print(arr == 20)  # [False, True, False]
print(arr != 20)  # [True, False, True]
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])
print(arr1 > arr2)  # [False, False, True]

[False  True  True]
[False  True False]
[ True False  True]
[False False  True]


In [101]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())  # 15
print(arr.max())  # 5
print(arr.min())  # 1
print(arr.std())  # 표준편차
print(arr.var())  # 분산\
print(arr.cumsum())

15
5
1
1.4142135623730951
2.0
[ 1  3  6 10 15]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [4,7,2]])
print(arr2d.sum(axis=0))  # [5, 7, 9] (각 열의 합)(행이 하나가 되는거)
print(arr2d.sum(axis=1))  # [6, 15] (각 행의 합)(열이 하나가 되는거)

[ 9 14 11]
[ 6 15 13]


In [105]:
arr = np.random.randn(1000)  # 평균 0, 표준편차 1인 정규분포 난수 1000개
print(np.mean(arr), np.std(arr))
arr = np.random.uniform(0, 1, 1000)  # 0과 1 사이의 균등분포 난수 1000개
print(np.mean(arr), np.std(arr))

-0.009801371720283409 1.0221984188896562
0.5090393603517533 0.28683861283408735


In [106]:
import numpy as np
arr = np.array([30, 10, 20, 40, 50])
sorted_arr = np.sort(arr)
print(sorted_arr)  # [10, 20, 30, 40, 50]

[10 20 30 40 50]


In [107]:
sorted_arr_desc = np.sort(arr)[::-1]
print(sorted_arr_desc)  # [50, 40, 30, 20, 10]

[50 40 30 20 10]


In [108]:
arr2d = np.array([[5, 2, 3], [8, 4, 1]])
sorted_arr2d = np.sort(arr2d)  # 행 단위로 정렬
print(sorted_arr2d)
# [[2, 3, 5],
#  [1, 4, 8]]

[[2 3 5]
 [1 4 8]]


In [109]:
sorted_arr_axis0 = np.sort(arr2d, axis=0)
print(sorted_arr_axis0)
sorted_arr_axis1 = np.sort(arr2d, axis=1)
print(sorted_arr_axis1)

[[5 2 1]
 [8 4 3]]
[[2 3 5]
 [1 4 8]]


In [110]:
arr = np.array([30, 10, 20])
sorted_indices = np.argsort(arr)
print(sorted_indices)
print(arr[sorted_indices])

[1 2 0]
[10 20 30]


In [112]:
arr2d = np.array([[3, 1, 2], [6, 4, 5]])
sorted_indices = np.argsort(arr2d, axis=1)
print(sorted_indices)

[[1 2 0]
 [1 2 0]]


In [113]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)

[1 2 3 4 5 6]


In [114]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
merged_arr = np.concatenate((arr1, arr2), axis=0)
print(merged_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [115]:
merged_arr = np.concatenate((arr1, arr2), axis=1)
print(merged_arr)

[[1 2 5 6]
 [3 4 7 8]]


In [118]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
merged_arr = np.vstack((arr1, arr2))
print(merged_arr)

merged_arr = np.hstack((arr1, arr2))
print(merged_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [119]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr)
stacked_arr = np.stack((arr1, arr2), axis=1)
print(stacked_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [3]:
import time
size = 1000000
python_list = list(range(size))

start_time = time.time()
python_list = [x * 2 for x in python_list]
print("Python 리스트 성능:", time.time() - start_time)

Python 리스트 성능: 0.0775153636932373


In [4]:
import numpy as np
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2
print("NumPy 배열 성능:", time.time() - start_time)

NumPy 배열 성능: 0.006960153579711914


In [122]:
size = 1000000
python_list = list(range(size))
result = []

start_time = time.time()
for x in python_list:
    result.append(x * 2)
print("반복문 성능:", time.time() - start_time)

반복문 성능: 0.05100107192993164


In [123]:
np_array = np.arange(size)

start_time = time.time()
np_array = np_array * 2  # 벡터화 연산
print("벡터화 성능:", time.time() - start_time)

벡터화 성능: 0.0031156539916992188


In [127]:
arr = np.array([1, 2, 3], dtype='int64')
print(arr.nbytes)  # 배열이 사용하는 메모리 크기 (bytes)
arr = np.array([1, 2, 3], dtype='int32')
print(arr.nbytes)  # 더 작은 메모리 사용

24
12


In [128]:
size = 100000000  # 1억 개의 요소
arr = np.random.rand(size)  # 난수 배열 생성

start_time = time.time()
result = np.sum(arr)  # 배열의 합 계산
print("대용량 데이터 합계 성능:", time.time() - start_time)

대용량 데이터 합계 성능: 0.06938838958740234


In [129]:
# 1GB 크기의 파일을 생성 후 메모리 맵핑 방식으로 읽기
size = 10**9
arr = np.memmap('large_file.dat', dtype='float32', mode='w+', shape=(size,))
arr[:100] = np.random.rand(100)  # 일부 데이터를 파일에 쓰기

# 파일을 메모리 맵핑하여 읽기
memmap_arr = np.memmap('large_file.dat', dtype='float32', mode='r', shape=(size,))
print(memmap_arr[:10])  # 메모리에 로드된 일부 데이터만 접근

[0.4418844  0.80631244 0.2482577  0.3767839  0.57731897 0.7963656
 0.02600295 0.08882202 0.6956881  0.44085705]


In [38]:
a = np.array([[[1,2,3]]])
b = np.array([[[1,2,3]]])
c = np.concatenate((a,b), axis=1)
print(c)

[[[1 2 3]
  [1 2 3]]]
